spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: '@Pan874974'
#    url: jdbc:mysql://39.106.78.112:3306/fss?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/fss?useUnicode=true&characterEncoding=utf8

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kg.fss.entity
logging:
  level:
    com.kg.fss.dao: debug
